# Generated by Django 3.2.4 on 2021-06-20 09:34

import TodoBackend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('title_id', models.UUIDField(default=TodoBackend.models.generateUUID, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=500)),
                ('status', models.TextField(default=False)),
            ],
        ),
    ]
