# Generated by Django 3.1.7 on 2021-06-20 05:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, default=None, max_length=254, unique=True)),
                ('recovery_email', models.EmailField(blank=True, default=None, max_length=254, unique=True)),
                ('password', models.CharField(max_length=32)),
                ('joining_date', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
    ]
